name: PR Preview

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Hexo and dependencies
      run: |
        npm install -g hexo-cli
        npm ci

    - name: Generate static files
      run: hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        destination_dir: previews/${{ github.event.number }}

    - name: Post PR comment with preview URL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
      run: |
        PREVIEW_URL="https://jpmessaging.github.io/blog/previews/${PR_NUMBER}"
        COMMENT="🚀 Preview URL: ${PREVIEW_URL}"
        curl -s -H "Authorization: token $GITHUB_TOKEN" -X POST -d "{\"body\":\"${COMMENT}\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"